import type { Integration } from "@/lib/types";

/**
 * Catalog of supported integrations. Each entry describes *what* it unlocks
 * for the agent system — the actual OAuth / API-Key wiring happens per
 * integration once the user provides the credentials.
 */
export const integrations: Integration[] = [
  // Communication ---------------------------------------------------------
  {
    id: "gmail",
    name: "Gmail",
    provider: "Google",
    category: "communication",
    description: "Posteingang lesen, antworten, Labels setzen, Versand.",
    badge: "G",
    color: "#ea4335",
    auth: "oauth",
    docsUrl: "https://developers.google.com/gmail/api",
    unlocks: "E-Mail-Triage, Zusammenfassungen, vorbereitete Antworten, Versand.",
  },
  {
    id: "outlook",
    name: "Outlook 365",
    provider: "Microsoft",
    category: "communication",
    description: "Microsoft-365-Postfach für E-Mail und Kontakte.",
    badge: "O",
    color: "#0078d4",
    auth: "oauth",
    docsUrl: "https://learn.microsoft.com/en-us/graph/api/resources/mail-api-overview",
    unlocks: "E-Mail-Triage, Zusammenfassungen, Antworten, Adressbuch.",
  },
  {
    id: "resend",
    name: "Resend",
    provider: "Resend",
    category: "communication",
    description: "Transaktionale E-Mails versenden (Briefings, Reports, Mahnungen).",
    badge: "R",
    color: "#000000",
    auth: "api_key",
    envVar: "RESEND_API_KEY",
    docsUrl: "https://resend.com/docs",
    unlocks: "Tägliche Briefings, automatische Reports und Mahnungen.",
  },
  // Calendar --------------------------------------------------------------
  {
    id: "google_calendar",
    name: "Google Calendar",
    provider: "Google",
    category: "calendar",
    description: "Termine lesen, anlegen, verschieben, Konflikte auflösen.",
    badge: "C",
    color: "#1a73e8",
    auth: "oauth",
    docsUrl: "https://developers.google.com/calendar",
    unlocks: "Terminplanung, Erinnerungen, Meeting-Vorbereitung.",
  },
  {
    id: "outlook_calendar",
    name: "Outlook Kalender",
    provider: "Microsoft",
    category: "calendar",
    description: "Microsoft-365-Kalender für Termine.",
    badge: "K",
    color: "#0078d4",
    auth: "oauth",
    unlocks: "Terminplanung, Erinnerungen, Meeting-Vorbereitung.",
  },
  // CRM -------------------------------------------------------------------
  {
    id: "hubspot",
    name: "HubSpot",
    provider: "HubSpot",
    category: "crm",
    description: "CRM für Kontakte, Deals, Pipelines.",
    badge: "H",
    color: "#ff7a59",
    auth: "oauth",
    docsUrl: "https://developers.hubspot.com",
    unlocks: "Lead-Bewertung, Follow-ups, Angebote, Pipeline-Reports.",
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    provider: "Pipedrive",
    category: "crm",
    description: "Sales-Pipeline-CRM für Mittelstand.",
    badge: "P",
    color: "#1a1a1a",
    auth: "oauth",
    unlocks: "Lead-Bewertung, Follow-ups, Pipeline-Reports.",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    provider: "Salesforce",
    category: "crm",
    description: "Enterprise-CRM.",
    badge: "S",
    color: "#00a1e0",
    auth: "oauth",
    unlocks: "Lead-Bewertung, Account-Management, Forecasts.",
  },
  // Accounting ------------------------------------------------------------
  {
    id: "lexoffice",
    name: "Lexoffice",
    provider: "Haufe",
    category: "accounting",
    description: "Buchhaltung, Rechnungen, Belege.",
    badge: "L",
    color: "#e30613",
    auth: "api_key",
    envVar: "LEXOFFICE_API_KEY",
    unlocks: "Rechnungen, Mahnungen, Belege, Monatsberichte.",
  },
  {
    id: "sevdesk",
    name: "sevDesk",
    provider: "sevDesk",
    category: "accounting",
    description: "Buchhaltung & Rechnungswesen.",
    badge: "SD",
    color: "#00a651",
    auth: "api_key",
    envVar: "SEVDESK_API_KEY",
    unlocks: "Rechnungen, Belege, Zahlungsabgleich.",
  },
  {
    id: "datev",
    name: "DATEV",
    provider: "DATEV",
    category: "accounting",
    description: "Übergabe an die Steuerberatung.",
    badge: "D",
    color: "#0091da",
    auth: "api_key",
    envVar: "DATEV_API_KEY",
    unlocks: "DATEV-Export, Steuerunterlagen vorbereiten.",
  },
  // Banking ---------------------------------------------------------------
  {
    id: "banking_finapi",
    name: "Banking (finAPI)",
    provider: "finAPI / PSD2",
    category: "banking",
    description: "Kontostände, Umsätze, Zahlungseingänge.",
    badge: "B",
    color: "#202020",
    auth: "oauth",
    unlocks: "Zahlungseingänge überwachen, Cashflow-Prognosen.",
  },
  // Telephony / Voice -----------------------------------------------------
  {
    id: "twilio",
    name: "Twilio",
    provider: "Twilio",
    category: "telephony",
    description: "Anrufe annehmen, SMS, eigene Telefonnummer.",
    badge: "T",
    color: "#f22f46",
    auth: "api_key",
    envVar: "TWILIO_AUTH_TOKEN",
    unlocks: "Telefonannahme, Rückrufe, SMS-Erinnerungen.",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    provider: "ElevenLabs",
    category: "voice",
    description: "Menschlich klingende Stimmen für Anrufe.",
    badge: "11",
    color: "#000000",
    auth: "api_key",
    envVar: "ELEVENLABS_API_KEY",
    unlocks: "Menschliche Stimme bei Telefonaten.",
  },
  {
    id: "deepgram",
    name: "Deepgram",
    provider: "Deepgram",
    category: "voice",
    description: "Live-Transkription von Anrufen und Meetings.",
    badge: "DG",
    color: "#13ef93",
    auth: "api_key",
    envVar: "DEEPGRAM_API_KEY",
    unlocks: "Live-Transkripte, Meeting-Protokolle, Anruf-Mitschnitte.",
  },
  // Support ---------------------------------------------------------------
  {
    id: "zendesk",
    name: "Zendesk",
    provider: "Zendesk",
    category: "support",
    description: "Helpdesk für Tickets und Wissensbasis.",
    badge: "Z",
    color: "#03363d",
    auth: "oauth",
    unlocks: "Ticket-Triage, FAQ-Antworten, Eskalationen.",
  },
  {
    id: "freshdesk",
    name: "Freshdesk",
    provider: "Freshworks",
    category: "support",
    description: "Helpdesk für Kundenservice-Teams.",
    badge: "F",
    color: "#25c16f",
    auth: "oauth",
    unlocks: "Ticket-Triage, Beschwerde-Eskalation.",
  },
  {
    id: "intercom",
    name: "Intercom",
    provider: "Intercom",
    category: "support",
    description: "Live-Chat und Support-Suite.",
    badge: "I",
    color: "#1f8ded",
    auth: "oauth",
    unlocks: "Live-Chat-Übernahme, Antworten, Eskalation.",
  },
  // Marketing -------------------------------------------------------------
  {
    id: "mailchimp",
    name: "Mailchimp",
    provider: "Intuit",
    category: "marketing",
    description: "Newsletter & E-Mail-Marketing.",
    badge: "M",
    color: "#ffe01b",
    auth: "oauth",
    unlocks: "Newsletter erstellen, planen, versenden.",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    provider: "Microsoft",
    category: "marketing",
    description: "Unternehmensseite und Posts.",
    badge: "LI",
    color: "#0a66c2",
    auth: "oauth",
    unlocks: "Posts erstellen und planen.",
  },
  {
    id: "x_twitter",
    name: "X (Twitter)",
    provider: "X",
    category: "marketing",
    description: "Posts und Mentions.",
    badge: "X",
    color: "#000000",
    auth: "oauth",
    unlocks: "Posts veröffentlichen, Mentions überwachen.",
  },
  // Documents / Collaboration --------------------------------------------
  {
    id: "google_drive",
    name: "Google Drive",
    provider: "Google",
    category: "documents",
    description: "Dokumentenablage.",
    badge: "GD",
    color: "#1a73e8",
    auth: "oauth",
    unlocks: "Dokumente automatisch ablegen und versionieren.",
  },
  {
    id: "notion",
    name: "Notion",
    provider: "Notion",
    category: "documents",
    description: "Wissensbasis und Dokumentation.",
    badge: "N",
    color: "#000000",
    auth: "oauth",
    unlocks: "Wissensbasis lesen und pflegen.",
  },
  {
    id: "slack",
    name: "Slack",
    provider: "Salesforce",
    category: "communication",
    description: "Team-Kommunikation und Benachrichtigungen.",
    badge: "Sl",
    color: "#4a154b",
    auth: "oauth",
    unlocks: "Benachrichtigungen und Status-Updates ins Team.",
  },
  // AI brain (internal — used by every agent) -----------------------------
  {
    id: "openai",
    name: "OpenAI",
    provider: "OpenAI",
    category: "ai",
    description: "Sprachmodell — die Denkleistung deiner Mitarbeiter.",
    badge: "AI",
    color: "#10a37f",
    auth: "api_key",
    envVar: "OPENAI_API_KEY",
    unlocks: "Echte KI-Antworten statt Demo-Modus.",
  },
];

export const integrationCategories: Record<
  import("@/lib/types").IntegrationCategory,
  string
> = {
  communication: "Kommunikation",
  calendar: "Kalender",
  crm: "CRM",
  accounting: "Buchhaltung",
  telephony: "Telefonie",
  voice: "Stimme & Transkription",
  marketing: "Marketing",
  support: "Kundenservice",
  documents: "Dokumente",
  banking: "Banking",
  ai: "KI-Gehirn",
};

export function getIntegration(id: string) {
  return integrations.find((i) => i.id === id);
}
